# Generated by Django 5.0.7 on 2025-05-01 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoriesID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('DateOrderPlace', models.DateTimeField(auto_now_add=True)),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusOrder',
            fields=[
                ('StatusOrderID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField(default=0)),
                ('Descrip', models.TextField(blank=True, null=True)),
                ('Image', models.CharField(blank=True, max_length=255, null=True)),
                ('CategoriesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('BookDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('DatePayment', models.DateTimeField(auto_now_add=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('StatusOrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.statusorder')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='StatusOrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.statusorder'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
