# Generated by Django 5.0.7 on 2025-05-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_account_role_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
