# Generated by Django 5.0.7 on 2025-05-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_accountid_account_accountid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetail',
            old_name='bookdetailID',
            new_name='bookDetailID',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryname',
            new_name='categoryName',
        ),
    ]
