# Generated by Django 5.0.7 on 2025-05-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account', unique=True),
        ),
    ]
